server:
  port: 8081
  servlet:
    context-path: '/cadastroprodutos/'
spring:
  application:
    name: sistema-cadastro-produtos
  datasource:
    url:  jdbc:postgresql://localhost:5432/cadastro-produtos
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
